/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PortfoliosRouteImport } from './routes/portfolios'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as ResultRouteImport } from './routes/result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosRoute = PortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolios': typeof PortfoliosRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/result': typeof ResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolios': typeof PortfoliosRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/result': typeof ResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolios': typeof PortfoliosRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/result': typeof ResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounts'
    | '/auth'
    | '/dashboard'
    | '/portfolio'
    | '/portfolios'
    | '/questionnaire'
    | '/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounts'
    | '/auth'
    | '/dashboard'
    | '/portfolio'
    | '/portfolios'
    | '/questionnaire'
    | '/result'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounts'
    | '/auth'
    | '/dashboard'
    | '/portfolio'
    | '/portfolios'
    | '/questionnaire'
    | '/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountsRoute: typeof AccountsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PortfolioRoute: typeof PortfolioRoute
  PortfoliosRoute: typeof PortfoliosRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  ResultRoute: typeof ResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios': {
      id: '/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof PortfoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountsRoute: AccountsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PortfolioRoute: PortfolioRoute,
  PortfoliosRoute: PortfoliosRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  ResultRoute: ResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
